// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCts8XcrD0_KeI99pYa7a3f2z91zORDLo4',
    appId: '1:508655506056:web:abe7721f2a718e80d5053d',
    messagingSenderId: '508655506056',
    projectId: 'nutriai-644c3',
    authDomain: 'nutriai-644c3.firebaseapp.com',
    storageBucket: 'nutriai-644c3.firebasestorage.app',
    measurementId: 'G-203LL0GHMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1MtpHlq1fn3e7eaTSi7yFAdWkJQ9WVpE',
    appId: '1:508655506056:android:55c1b99324c7507ad5053d',
    messagingSenderId: '508655506056',
    projectId: 'nutriai-644c3',
    storageBucket: 'nutriai-644c3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD32MeQoZLPFp16DgsB0DNJtSTukAbC_N4',
    appId: '1:508655506056:ios:5b4ae4bfa6161195d5053d',
    messagingSenderId: '508655506056',
    projectId: 'nutriai-644c3',
    storageBucket: 'nutriai-644c3.firebasestorage.app',
    androidClientId: '508655506056-ulpb9qud2ott7oi3b5ci47475krk5kfh.apps.googleusercontent.com',
    iosClientId: '508655506056-57lrmo98jciolpr9non5cbpc5bqbj3v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriai',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD32MeQoZLPFp16DgsB0DNJtSTukAbC_N4',
    appId: '1:508655506056:ios:5b4ae4bfa6161195d5053d',
    messagingSenderId: '508655506056',
    projectId: 'nutriai-644c3',
    storageBucket: 'nutriai-644c3.firebasestorage.app',
    androidClientId: '508655506056-ulpb9qud2ott7oi3b5ci47475krk5kfh.apps.googleusercontent.com',
    iosClientId: '508655506056-57lrmo98jciolpr9non5cbpc5bqbj3v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCts8XcrD0_KeI99pYa7a3f2z91zORDLo4',
    appId: '1:508655506056:web:797016bee9a1d1bdd5053d',
    messagingSenderId: '508655506056',
    projectId: 'nutriai-644c3',
    authDomain: 'nutriai-644c3.firebaseapp.com',
    storageBucket: 'nutriai-644c3.firebasestorage.app',
    measurementId: 'G-BVC6MH3JDF',
  );
}
